import React, { useEffect, useMemo, useState } from 'react';
import { createUserWithEmailAndPassword, signInWithEmailAndPassword, signInWithPopup, updateProfile, User as FirebaseUser } from 'firebase/auth';
import { doc, getDoc, setDoc } from 'firebase/firestore';
import { AnimatePresence, motion } from 'motion/react';
import { ArrowLeft, ArrowRight, Check, CheckCircle2, Lock, Mail, Rocket, Search, Sparkles, UserRound, UsersRound, X } from 'lucide-react';
import { auth, db, googleProvider } from '../lib/firebase';
import { User, UserRole } from '../types';

interface AuthModalProps { isOpen: boolean; onClose: () => void; onSuccess: (user: User) => void; onOpenLegal: () => void; initialMode?: 'login' | 'signup'; }
const skillsList = ['AI & Machine Learning','Android Development','Analytics','Brand Strategy','Business Development','Community Building','Content Writing','Copywriting','Customer Success','Data Science','DevOps','Email Marketing','Finance','Frontend Development','Full-stack Development','Graphic Design','Growth Marketing','HR & Recruiting','Influencer Marketing','iOS Development','Legal','Motion Design','No-code','Operations','Product Design','Product Management','Public Relations','Python','React','Sales','SEO','Social Media','UI/UX Design','User Research','Video Editing','Web Development'];
const avatar = (name: string) => `https://ui-avatars.com/api/?name=${encodeURIComponent(name || 'Member')}&background=5B5CF0&color=fff&bold=true`;

export const AuthModal: React.FC<AuthModalProps> = ({ isOpen, onClose, onSuccess, onOpenLegal, initialMode = 'login' }) => {
  const [mode, setMode] = useState<'login'|'signup'>(initialMode), [step, setStep] = useState(1), [email, setEmail] = useState(''), [password, setPassword] = useState(''), [name, setName] = useState('');
  const [role, setRole] = useState<UserRole>('founder'), [skills, setSkills] = useState<string[]>([]), [query, setQuery] = useState(''), [story, setStory] = useState(''), [goal, setGoal] = useState(''), [startup, setStartup] = useState(''), [industry, setIndustry] = useState(''), [stage, setStage] = useState('Idea'), [availability, setAvailability] = useState('10–20 hours / week');
  const [googleUser, setGoogleUser] = useState<FirebaseUser|null>(null), [error, setError] = useState(''), [loading, setLoading] = useState(false);
  useEffect(() => { if (isOpen) { setMode(initialMode); setStep(1); setError(''); } }, [isOpen, initialMode]);
  const matches = useMemo(() => skillsList.filter(x => x.toLowerCase().includes(query.toLowerCase()) && !skills.includes(x)).slice(0, 6), [query, skills]);
  const change = (next: 'login'|'signup') => { setMode(next); setStep(1); setError(''); setGoogleUser(null); };
  const addSkill = (x: string) => { if (x.trim() && !skills.includes(x.trim())) setSkills([...skills, x.trim()]); setQuery(''); };
  const saveProfile = async (fu: FirebaseUser) => {
    const displayName = name.trim() || fu.displayName || 'New member';
    if (name.trim() && fu.displayName !== displayName) await updateProfile(fu, { displayName });
    const onboarding = role === 'founder'
      ? { story, goal, startupName: startup, startupStage: stage, industry }
      : { story, goal, availability };
    const profile: User = { id: fu.uid, name: displayName, email: fu.email || email, role, avatar: fu.photoURL || avatar(displayName), title: role === 'founder' ? 'Startup founder' : 'Startup builder', bio: story, skills, onboarding };
    await setDoc(doc(db, 'users', fu.uid), { ...profile, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() }, { merge: true }); onSuccess(profile); onClose();
  };
  const login = async (e: React.FormEvent) => { e.preventDefault(); setLoading(true); setError(''); try { const { user } = await signInWithEmailAndPassword(auth, email, password); const snap = await getDoc(doc(db, 'users', user.uid)); onSuccess(snap.exists() ? snap.data() as User : { id: user.uid, name: user.displayName || 'Member', email: user.email || email, role: 'employee', avatar: user.photoURL || avatar(user.displayName || 'Member'), title: 'Startup builder', bio: '', skills: [] }); onClose(); } catch (e:any) { setError(e.message.replace('Firebase: ', '')); } finally { setLoading(false); } };
  const google = async () => { setLoading(true); setError(''); try { const { user } = await signInWithPopup(auth, googleProvider); const snap = await getDoc(doc(db, 'users', user.uid)); if (snap.exists()) { onSuccess(snap.data() as User); onClose(); } else { setGoogleUser(user); setName(user.displayName || ''); setEmail(user.email || ''); setMode('signup'); setStep(2); } } catch (e:any) { setError(e.message.replace('Firebase: ', '')); } finally { setLoading(false); } };
  const first = async (e: React.FormEvent) => { e.preventDefault(); if (!name.trim()) return setError('Please tell us what to call you.'); if (googleUser) return setStep(2); setLoading(true); setError(''); try { const { user } = await createUserWithEmailAndPassword(auth, email, password); await updateProfile(user, { displayName: name.trim() }); setGoogleUser(user); setStep(2); } catch (e:any) { setError(e.message.replace('Firebase: ', '')); } finally { setLoading(false); } };
  const done = async () => { if (!googleUser) return; setLoading(true); try { await saveProfile(googleUser); } catch (e:any) { setError(e.message.replace('Firebase: ', '')); } finally { setLoading(false); } };
  return <AnimatePresence>{isOpen && <motion.div initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} className="fixed inset-0 z-50 overflow-y-auto bg-[#080b1b]/90 p-4 backdrop-blur-xl"><div className="pointer-events-none absolute -top-20 left-1/4 h-96 w-96 rounded-full bg-violet-600/25 blur-[110px]"/><motion.div initial={{opacity:0,y:24}} animate={{opacity:1,y:0}} className="relative mx-auto my-4 w-full max-w-5xl overflow-hidden rounded-[32px] border border-white/10 bg-[#10142b] shadow-2xl lg:grid lg:grid-cols-[.82fr_1.18fr]">
    <aside className="hidden min-h-[640px] flex-col justify-between border-r border-white/10 bg-gradient-to-b from-violet-600/25 to-[#10142b] p-10 lg:flex"><div><div className="flex items-center gap-2 text-white"><span className="grid h-10 w-10 place-items-center rounded-xl bg-white text-violet-700"><Sparkles className="h-5 w-5"/></span><b className="text-xl">MORN<span className="text-violet-300">AI</span></b></div><p className="mt-24 text-xs font-bold uppercase tracking-[.2em] text-violet-200">Your startup operating system</p><h1 className="mt-4 text-4xl font-bold leading-tight text-white">Build with a team that never loses context.</h1><p className="mt-5 text-sm leading-6 text-slate-300">AI roles, a living roadmap, and the people to turn momentum into outcomes.</p></div><div className="rounded-2xl border border-white/10 bg-white/5 p-5 text-sm text-slate-200">“It feels like having a strategist in every room.”</div></aside>
    <section className="min-h-[640px] p-6 sm:p-10"><button onClick={onClose} className="absolute right-5 top-5 text-slate-400 hover:text-white"><X/></button>{mode==='signup' && <div className="mb-8 mr-10"><div className="mb-2 flex justify-between text-xs font-semibold text-slate-400"><span>Set up your space</span><span>{step}/5</span></div><div className="h-1.5 rounded-full bg-white/10"><div className="h-full rounded-full bg-gradient-to-r from-violet-400 to-cyan-300" style={{width:`${(step-1)*25}%`}}/></div></div>}
    {mode==='login' ? <div className="mx-auto max-w-md pt-12"><Pill>Welcome back</Pill><h2 className="mt-5 text-3xl font-bold text-white">Continue building.</h2><p className="mt-2 text-sm text-slate-400">Your roadmap, team context, and next move are ready.</p><form onSubmit={login} className="mt-8 space-y-4"><Field icon={<Mail/>} type="email" placeholder="Email address" value={email} set={setEmail}/><Field icon={<Lock/>} type="password" placeholder="Password" value={password} set={setPassword}/><Error text={error}/><Primary loading={loading}>Log in <ArrowRight className="h-4 w-4"/></Primary></form><Divider/><Google onClick={google} loading={loading}/><p className="mt-7 text-center text-sm text-slate-400">New to MornAI? <button onClick={()=>change('signup')} className="font-bold text-violet-300">Create your account</button></p></div> : <div className="mx-auto max-w-xl pt-3">
    {step===1 && <><Head n="01" title="Start your workspace" text="A few details to make this feel like yours from day one."/><form onSubmit={first} className="mt-7 space-y-4"><Field icon={<UserRound/>} type="text" placeholder="Your full name" value={name} set={setName}/><Field icon={<Mail/>} type="email" placeholder="Email address" value={email} set={setEmail} disabled={!!googleUser}/>{!googleUser&&<Field icon={<Lock/>} type="password" placeholder="Create a password (6+ characters)" value={password} set={setPassword}/>}<Error text={error}/><Primary loading={loading}>Continue <ArrowRight className="h-4 w-4"/></Primary></form>{!googleUser&&<><Divider/><Google onClick={google} loading={loading}/></>}<p className="mt-6 text-center text-sm text-slate-400">Already a member? <button onClick={()=>change('login')} className="font-bold text-violet-300">Log in</button></p></>}
    {step===2 && <><Head n="02" title="What brings you here?" text="This shapes the tools and people we put in front of you."/><div className="mt-7 grid gap-4 sm:grid-cols-2"><Role selected={role==='founder'} click={()=>setRole('founder')} icon={<Rocket/>} title="I’m building a startup" text="I need strategy, a roadmap, and exceptional people."/><Role selected={role==='employee'} click={()=>setRole('employee')} icon={<UsersRound/>} title="I want to join one" text="I have skills and want meaningful startup work."/></div><Next back={()=>setStep(1)} next={()=>setStep(3)}/></>}
    {step===3 && <><Head n="03" title="Your unfair advantages" text="Search and add the skills you want your future team to know about."/><div className="relative mt-6"><Search className="absolute left-4 top-4 h-5 w-5 text-slate-500"/><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();addSkill(query)}}} placeholder="Search skills — e.g. product design, Python, sales" className="w-full rounded-2xl border border-white/10 bg-white/5 py-4 pl-12 pr-4 text-white outline-none placeholder:text-slate-500"/>{query&&<div className="absolute z-10 mt-2 w-full overflow-hidden rounded-xl border border-white/10 bg-[#1b2040]">{matches.map(x=><button key={x} onClick={()=>addSkill(x)} className="block w-full px-4 py-3 text-left text-sm text-slate-200 hover:bg-white/5">{x}</button>)}{!matches.length&&<button onClick={()=>addSkill(query)} className="w-full px-4 py-3 text-left text-sm text-violet-300">Add “{query}”</button>}</div>}</div><div className="mt-5 flex min-h-16 flex-wrap gap-2">{skills.map(x=><button key={x} onClick={()=>setSkills(skills.filter(s=>s!==x))} className="rounded-full bg-violet-500/15 px-3 py-1.5 text-sm text-violet-100">{x} ×</button>)}{!skills.length&&<p className="pt-2 text-sm text-slate-500">Choose a few — you can update these later.</p>}</div><Next back={()=>setStep(2)} next={()=>setStep(4)} disabled={!skills.length}/></>}
    {step===4 && <><Head n="04" title={role==='founder'?'Tell us about the mission':'Tell us what drives you'} text={role==='founder'?'We’ll turn this into the first context for your AI leadership team.':'We’ll surface opportunities where you can actually thrive.'}/>{role==='founder'?<div className="mt-6 grid gap-4 sm:grid-cols-2"><Text p="Startup or project name" v={startup} s={setStartup}/><Text p="Industry — e.g. health, fintech" v={industry} s={setIndustry}/><select value={stage} onChange={e=>setStage(e.target.value)} className="rounded-xl border border-white/10 bg-white/5 px-4 py-3 text-sm text-slate-200"><option>Idea</option><option>MVP</option><option>Early traction</option><option>Growing team</option></select><Text p="Your biggest goal for the next 90 days" v={goal} s={setGoal}/></div>:<div className="mt-6 space-y-4"><select value={availability} onChange={e=>setAvailability(e.target.value)} className="w-full rounded-xl border border-white/10 bg-white/5 px-4 py-3 text-sm text-slate-200"><option>5–10 hours / week</option><option>10–20 hours / week</option><option>20+ hours / week</option><option>Full-time</option></select><Text p="What kind of startup problem do you want to solve?" v={goal} s={setGoal}/></div>}<Next back={()=>setStep(3)} next={()=>setStep(5)}/></>}
    {step===5 && <><Head n="05" title="The human context" text="Share as much as you’re comfortable with. Your AI teammate uses it to give advice that fits your life."/><textarea value={story} onChange={e=>setStory(e.target.value)} placeholder="What should your AI team understand about your experience, motivation, constraints, and how you like to work?" rows={6} className="mt-6 w-full rounded-2xl border border-white/10 bg-white/5 p-4 text-sm leading-6 text-white outline-none placeholder:text-slate-500"/><div className="mt-5 rounded-2xl bg-emerald-400/5 p-4 text-sm text-emerald-100"><CheckCircle2 className="mr-2 inline h-4 w-4"/>You’re creating a private, evolving context — not a static profile.</div><Error text={error}/><Next back={()=>setStep(4)} next={done} label="Create my workspace" loading={loading}/></>}
    </div>}</section></motion.div><button onClick={onOpenLegal} className="relative mx-auto block text-xs text-slate-500">Terms & Privacy</button></motion.div>}</AnimatePresence>;
};
const Head=({n,title,text}:any)=><><span className="text-xs font-bold tracking-[.2em] text-violet-300">{n} / 05</span><h2 className="mt-3 text-3xl font-bold text-white">{title}</h2><p className="mt-2 text-sm leading-6 text-slate-400">{text}</p></>;
const Pill=({children}:any)=><span className="inline-flex gap-2 rounded-full bg-violet-500/10 px-3 py-1 text-xs font-bold text-violet-300"><Sparkles className="h-3.5 w-3.5"/>{children}</span>;
const Field=({icon,type,placeholder,value,set,disabled}:any)=><div className="relative"><span className="absolute left-4 top-3.5 text-slate-500 [&>svg]:h-5 [&>svg]:w-5">{icon}</span><input required disabled={disabled} type={type} placeholder={placeholder} value={value} onChange={e=>set(e.target.value)} className="w-full rounded-xl border border-white/10 bg-white/5 py-3 pl-12 pr-4 text-sm text-white outline-none placeholder:text-slate-500 disabled:opacity-60"/></div>;
const Text=({p,v,s}:any)=><input value={v} onChange={e=>s(e.target.value)} placeholder={p} className="rounded-xl border border-white/10 bg-white/5 px-4 py-3 text-sm text-white outline-none placeholder:text-slate-500"/>;
const Error=({text}:any)=>text?<p className="mt-3 rounded-xl bg-rose-500/10 px-3 py-2 text-xs text-rose-200">{text}</p>:null;
const Primary=({children,loading}:any)=><button disabled={loading} className="flex w-full items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-violet-500 to-indigo-500 py-3.5 text-sm font-bold text-white disabled:opacity-60">{loading?'Working…':children}</button>;
const Divider=()=> <div className="my-6 flex items-center gap-3"><i className="h-px flex-1 bg-white/10"/><span className="text-[10px] font-bold text-slate-500">OR</span><i className="h-px flex-1 bg-white/10"/></div>;
const Google=({onClick,loading}:any)=><button onClick={onClick} disabled={loading} className="flex w-full items-center justify-center gap-3 rounded-xl border border-white/10 bg-white/5 py-3 text-sm font-bold text-white"><span className="grid h-5 w-5 place-items-center rounded-full bg-white text-xs font-black text-blue-600">G</span>Continue with Google</button>;
const Role=({selected,click,icon,title,text}:any)=><button onClick={click} className={`rounded-2xl border p-5 text-left ${selected?'border-violet-400 bg-violet-500/15':'border-white/10 bg-white/[.03]'}`}><span className={`mb-7 grid h-10 w-10 place-items-center rounded-xl ${selected?'bg-violet-400 text-violet-950':'bg-white/10 text-slate-300'}`}>{icon}</span><b className="block text-white">{title}</b><p className="mt-2 text-sm text-slate-400">{text}</p>{selected&&<span className="mt-5 inline-flex items-center gap-1 text-xs font-bold text-violet-300"><Check className="h-3.5 w-3.5"/>Selected</span>}</button>;
const Next=({back,next,disabled,label='Continue',loading}:any)=><div className="mt-9 flex justify-between"><button onClick={back} className="inline-flex items-center gap-1 text-sm font-semibold text-slate-400"><ArrowLeft className="h-4 w-4"/>Back</button><button disabled={disabled||loading} onClick={next} className="inline-flex items-center gap-2 rounded-xl bg-white px-5 py-3 text-sm font-bold text-slate-900 disabled:opacity-40">{loading?'Creating…':label}<ArrowRight className="h-4 w-4"/></button></div>;
