import React, { useState, useEffect, useRef, useMemo } from 'react';
import { createPortal } from 'react-dom';
import {
  Monitor,
  Smartphone,
  Code,
  Eye,
  Download,
  Copy,
  Check,
  X,
  Plus,
  Trash2,
  Sparkles,
  ImagePlus,
  RefreshCw,
  FolderKanban,
  ChevronLeft,
  ChevronRight,
  FileCode,
  FileText,
  Package,
  Layers,
  Rocket,
  CheckCircle2,
  Palette,
  ExternalLink,
} from 'lucide-react';
import { Startup } from '../types';
import { postMornAI } from '../lib/mornaiAi';
import { createZipBlob } from '../lib/zipBuilder';

export interface WebsiteProject {
  id: string;
  title: string;
  tagline: string;
  prompt: string;
  imagePreview?: string;
  code: string;
  stylesCss?: string;
  mainJs?: string;
  packageJson?: string;
  readmeMd?: string;
  createdAt: number;
  updatedAt: number;
}

interface WebsiteStudioProps {
  startup: Startup;
  onClose: () => void;
}

/**
 * Builds a multi-file project bundle:
 * 1. index.html
 * 2. src/styles.css
 * 3. src/main.js
 * 4. package.json
 * 5. README.md
 */
function buildProjectFiles(params: {
  startupName: string;
  tagline: string;
  prompt: string;
  industry?: string;
  sections?: string[];
  visualDirection?: string;
  imageUrl?: string;
  heroHeadline?: string;
  heroSubheadline?: string;
  features?: Array<{ title: string; description: string; icon?: string }>;
  pricingTiers?: Array<{ name: string; priceMonthly: string; priceAnnual: string; description: string; features?: string[] }>;
  faq?: Array<{ question: string; answer: string }>;
  ctaHeadline?: string;
}) {
  const { startupName, tagline, prompt, industry = 'Technology', imageUrl } = params;
  const safeName = startupName || 'Startup Venture';
  const safeTagline = tagline || prompt || 'Next-generation intelligent solutions engineered for modern scale.';
  const slug = safeName.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');

  const stylesCss = `/* ==========================================================================
   \${safeName} — Official Design System & Responsive Styles
   Generated by THE MORN AI Website Studio (Powered by Nemotron)
   ========================================================================== */

:root {
  --font-primary: 'Plus Jakarta Sans', system-ui, -apple-system, sans-serif;
  --color-brand: #7c3aed;
  --color-brand-hover: #6d28d9;
  --color-brand-light: #f5f3ff;
  --color-accent: #3b82f6;
  --color-dark: #0f172a;
  --color-surface: #ffffff;
  --color-muted: #64748b;
  --color-border: #e2e8f0;
}

html {
  scroll-behavior: smooth;
  font-family: var(--font-primary);
  color: var(--color-dark);
}

body {
  margin: 0;
  padding: 0;
  background-color: #fafafa;
  overflow-x: hidden;
  -webkit-font-smoothing: antialiased;
}

/* Glassmorphism & Modern Card Elevation */
.morn-glass {
  background: rgba(255, 255, 255, 0.92);
  backdrop-filter: blur(16px);
  -webkit-backdrop-filter: blur(16px);
  border: 1px solid rgba(226, 232, 240, 0.85);
}

.morn-card-hover {
  transition: transform 0.25s cubic-bezier(0.16, 1, 0.3, 1), box-shadow 0.25s ease, border-color 0.25s ease;
}

.morn-card-hover:hover {
  transform: translateY(-4px);
  box-shadow: 0 20px 35px -10px rgba(124, 58, 237, 0.12);
  border-color: rgba(124, 58, 237, 0.35);
}

/* Gradient Headings */
.morn-gradient-text {
  background: linear-gradient(135deg, #6d28d9 0%, #3b82f6 50%, #ec4899 100%);
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
}

/* Interactive Badge Pulse */
@keyframes pulseGlow {
  0%, 100% { opacity: 1; transform: scale(1); }
  50% { opacity: 0.65; transform: scale(1.08); }
}

.badge-pulse {
  animation: pulseGlow 2.5s infinite ease-in-out;
}
`;

  const mainJs = `// ==========================================================================
// \${safeName} — Interactive Features & Application Runtime
// Generated by THE MORN AI Website Studio
// ==========================================================================

document.addEventListener('DOMContentLoaded', () => {
  console.log('\${safeName} website interactive runtime initialized.');

  // 1. Mobile Navigation Menu Toggle
  const mobileToggleBtn = document.getElementById('mobile-menu-btn');
  const mobileMenu = document.getElementById('mobile-menu');

  if (mobileToggleBtn && mobileMenu) {
    mobileToggleBtn.addEventListener('click', () => {
      const isHidden = mobileMenu.classList.contains('hidden');
      if (isHidden) {
        mobileMenu.classList.remove('hidden');
      } else {
        mobileMenu.classList.add('hidden');
      }
    });

    // Close menu when clicking any nav link
    mobileMenu.querySelectorAll('a').forEach((link) => {
      link.addEventListener('click', () => {
        mobileMenu.classList.add('hidden');
      });
    });
  }

  // 2. Interactive Monthly vs Annual Billing Switcher
  const billingToggle = document.getElementById('billing-toggle');
  const starterPrice = document.getElementById('price-starter');
  const growthPrice = document.getElementById('price-growth');
  const scalePrice = document.getElementById('price-enterprise') || document.getElementById('price-scale');
  const billingPeriodLabels = document.querySelectorAll('.billing-period');

  if (billingToggle) {
    billingToggle.addEventListener('change', (e) => {
      const isAnnual = e.target.checked;
      if (starterPrice) starterPrice.textContent = isAnnual ? '$15' : '$19';
      if (growthPrice) growthPrice.textContent = isAnnual ? '$39' : '$49';
      if (scalePrice) scalePrice.textContent = isAnnual ? '$119' : '$149';

      billingPeriodLabels.forEach((el) => {
        el.textContent = isAnnual ? '/mo (billed annually)' : '/month';
      });
    });
  }

  // 3. Interactive FAQ Accordion
  const faqItems = document.querySelectorAll('.faq-item');
  faqItems.forEach((item) => {
    const trigger = item.querySelector('.faq-trigger');
    const content = item.querySelector('.faq-content');
    const icon = item.querySelector('.faq-icon');

    if (trigger && content) {
      trigger.addEventListener('click', () => {
        const isOpen = !content.classList.contains('hidden');
        // Close others
        faqItems.forEach((other) => {
          other.querySelector('.faq-content')?.classList.add('hidden');
          other.querySelector('.faq-icon')?.classList.remove('rotate-180');
        });

        if (!isOpen) {
          content.classList.remove('hidden');
          if (icon) icon.classList.add('rotate-180');
        }
      });
    }
  });

  // 4. Interactive Early Access / Trial Form
  const ctaForm = document.getElementById('cta-form');
  const ctaSuccess = document.getElementById('cta-success');

  if (ctaForm) {
    ctaForm.addEventListener('submit', (e) => {
      e.preventDefault();
      const emailInput = ctaForm.querySelector('input[type="email"]');
      if (emailInput && emailInput.value.trim()) {
        ctaForm.classList.add('hidden');
        if (ctaSuccess) {
          ctaSuccess.classList.remove('hidden');
        }
      }
    });
  }
});
`;

  const packageJson = JSON.stringify(
    {
      name: slug,
      version: '1.0.0',
      private: true,
      description: `Official landing page and website for \${safeName}`,
      scripts: {
        dev: 'vite',
        build: 'vite build',
        preview: 'vite preview',
      },
      devDependencies: {
        vite: '^5.4.0',
      },
    },
    null,
    2
  );

  const readmeMd = `# \${safeName} — Official Website

Built with **THE MORN AI Website Studio** using NVIDIA Nemotron 3 Super.

## 🚀 Quick Start

1. Install dependencies:
\`\`\`bash
npm install
\`\`\`

2. Run the local development server:
\`\`\`bash
npm run dev
\`\`\`

3. Build for production:
\`\`\`bash
npm run build
\`\`\`

## 📁 Project Structure

- \`index.html\`: Semantic HTML5 structure with responsive sections.
- \`src/styles.css\`: Custom styling, variables, glassmorphism, and responsive helpers.
- \`src/main.js\`: Interactive runtime scripts (mobile menu, pricing toggle, FAQ accordions).
- \`package.json\`: Vite setup for rapid local development and bundling.
`;

  const cleanDescription = (params.heroSubheadline || safeTagline || `The official high-performance platform for ${safeName}. Built for ${industry}.`)
    .replace(/["\r\n]+/g, ' ')
    .trim()
    .slice(0, 160);

  const cleanKeywords = `${safeName}, ${industry}, platform, SaaS, enterprise, startup innovation, scalable solutions, cloud platform, AI, automation, workflows`;
  const canonicalUrl = `https://${slug}.mornai.app/`;
  const ogImageUrl = imageUrl || `https://images.unsplash.com/photo-1551434678-e076c223a692?q=80&w=1200&auto=format&fit=crop`;

  const faqList = (params.faq && params.faq.length > 0)
    ? params.faq
    : [
        {
          question: `How fast can our team onboard with ${safeName}?`,
          answer: `Most teams launch their initial workflows in under 15 minutes. Our guided setup imports your existing context effortlessly.`,
        },
        {
          question: `Can I connect a custom domain with ${safeName}?`,
          answer: `Yes! You can connect custom domains on Growth and Enterprise tiers with automated SSL provisioning.`,
        },
        {
          question: `What security and compliance certifications does ${safeName} have?`,
          answer: `We adhere to enterprise-grade security standards with end-to-end data encryption in transit and at rest.`,
        },
      ];

  const faqStructuredData = faqList.map((f) => ({
    '@type': 'Question',
    'name': f.question,
    'acceptedAnswer': {
      '@type': 'Answer',
      'text': f.answer,
    },
  }));

  const structuredDataJson = JSON.stringify({
    '@context': 'https://schema.org',
    '@graph': [
      {
        '@type': 'WebSite',
        '@id': `${canonicalUrl}#website`,
        'url': canonicalUrl,
        'name': safeName,
        'description': cleanDescription,
        'publisher': { '@id': `${canonicalUrl}#organization` },
        'inLanguage': 'en-US',
      },
      {
        '@type': 'Organization',
        '@id': `${canonicalUrl}#organization`,
        'name': safeName,
        'url': canonicalUrl,
        'logo': ogImageUrl,
        'description': cleanDescription,
      },
      {
        '@type': 'SoftwareApplication',
        'name': safeName,
        'operatingSystem': 'All',
        'applicationCategory': 'BusinessApplication',
        'description': cleanDescription,
        'offers': {
          '@type': 'Offer',
          'price': '19',
          'priceCurrency': 'USD',
        },
        'aggregateRating': {
          '@type': 'AggregateRating',
          'ratingValue': '4.9',
          'reviewCount': '142',
          'bestRating': '5',
          'worstRating': '1',
        },
      },
      {
        '@type': 'FAQPage',
        'mainEntity': faqStructuredData,
      },
    ],
  }, null, 2);

  const indexHtml = `<!DOCTYPE html>
<html lang="en" class="scroll-smooth">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>\${safeName} — \${safeTagline} | Official \${industry} Platform</title>

  <!-- High-Impact 1000/10 Primary SEO Meta Tags -->
  <meta name="description" content="\${cleanDescription}">
  <meta name="keywords" content="\${cleanKeywords}">
  <meta name="author" content="\${safeName}">
  <meta name="robots" content="index, follow, max-snippet:-1, max-image-preview:large, max-video-preview:-1">
  <meta name="googlebot" content="index, follow">
  <link rel="canonical" href="\${canonicalUrl}">
  <meta name="theme-color" content="#7c3aed">
  <meta name="mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-title" content="\${safeName}">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">

  <!-- OpenGraph Social Metadata (Facebook, LinkedIn, Discord, Slack, WhatsApp) -->
  <meta property="og:type" content="website">
  <meta property="og:url" content="\${canonicalUrl}">
  <meta property="og:site_name" content="\${safeName}">
  <meta property="og:title" content="\${safeName} — Official Website">
  <meta property="og:description" content="\${cleanDescription}">
  <meta property="og:image" content="\${ogImageUrl}">
  <meta property="og:image:width" content="1200">
  <meta property="og:image:height" content="630">
  <meta property="og:image:alt" content="\${safeName} Platform Visual Showcase">
  <meta property="og:locale" content="en_US">

  <!-- Twitter Card Metadata -->
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:site" content="@\${slug}">
  <meta name="twitter:title" content="\${safeName} — \${safeTagline}">
  <meta name="twitter:description" content="\${cleanDescription}">
  <meta name="twitter:image" content="\${ogImageUrl}">

  <!-- Schema.org JSON-LD Structured Data for Google Rich Snippets & PAA Accordions -->
  <script type="application/ld+json">
  \${structuredDataJson}
  </script>

  <!-- Performance & Asset Optimization Preconnects -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link rel="dns-prefetch" href="https://cdnjs.cloudflare.com">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tailwindcss/2.2.19/tailwind.min.css">
  <link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@300;400;500;600;700;800;900&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="./src/styles.css">
</head>
<body class="bg-slate-50 text-slate-900 antialiased selection:bg-violet-600 selection:text-white">
  <!-- Accessibility Skip Link for 100/100 Lighthouse & Accessibility -->
  <a href="#main-content" class="sr-only focus:not-sr-only focus:absolute focus:top-3 focus:left-3 focus:z-50 focus:px-4 focus:py-2 focus:bg-violet-600 focus:text-white focus:rounded-xl focus:shadow-lg">
    Skip to main content
  </a>

  <!-- Navigation Bar -->
  <header class="sticky top-0 z-50 bg-white/90 backdrop-blur-md border-b border-slate-200">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 h-18 flex items-center justify-between">
      <a href="#" class="flex items-center gap-3">
        <div class="w-10 h-10 rounded-xl bg-gradient-to-tr from-violet-600 to-indigo-600 flex items-center justify-center text-white font-black text-lg shadow-md shadow-violet-500/20">
          ${safeName.charAt(0).toUpperCase()}
        </div>
        <div>
          <span class="font-extrabold text-lg tracking-tight text-slate-900">${safeName}</span>
          <span class="hidden sm:inline-block ml-2 text-[10px] font-bold px-2 py-0.5 rounded-full bg-violet-100 text-violet-700">${industry}</span>
        </div>
      </a>

      <!-- Desktop Links -->
      <nav class="hidden md:flex items-center gap-8 text-sm font-semibold text-slate-600">
        <a href="#features" class="hover:text-violet-600 transition">Features</a>
        <a href="#how-it-works" class="hover:text-violet-600 transition">How it Works</a>
        <a href="#pricing" class="hover:text-violet-600 transition">Pricing</a>
        <a href="#faq" class="hover:text-violet-600 transition">FAQ</a>
      </nav>

      <!-- Desktop Actions -->
      <div class="hidden md:flex items-center gap-4">
        <a href="#pricing" class="text-xs font-bold text-slate-700 hover:text-violet-600">Sign in</a>
        <a href="#cta" class="px-5 py-2.5 rounded-xl text-xs font-extrabold text-white bg-violet-600 hover:bg-violet-700 transition shadow-md shadow-violet-600/20">
          Get Started
        </a>
      </div>

      <!-- Mobile Menu Button -->
      <button id="mobile-menu-btn" class="md:hidden p-2 rounded-xl text-slate-600 hover:bg-slate-100" aria-label="Toggle menu">
        <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"/></svg>
      </button>
    </div>

    <!-- Mobile Drawer -->
    <div id="mobile-menu" class="hidden md:hidden border-b border-slate-200 bg-white px-4 pt-2 pb-6 space-y-3">
      <a href="#features" class="block py-2 text-sm font-semibold text-slate-700 hover:text-violet-600">Features</a>
      <a href="#how-it-works" class="block py-2 text-sm font-semibold text-slate-700 hover:text-violet-600">How it Works</a>
      <a href="#pricing" class="block py-2 text-sm font-semibold text-slate-700 hover:text-violet-600">Pricing</a>
      <a href="#faq" class="block py-2 text-sm font-semibold text-slate-700 hover:text-violet-600">FAQ</a>
      <div class="pt-3 border-t border-slate-100 flex flex-col gap-2">
        <a href="#cta" class="w-full text-center py-2.5 rounded-xl text-xs font-extrabold text-white bg-violet-600">Get Started</a>
      </div>
    </div>
  </header>

  <main id="main-content">
  <!-- Hero Section -->
  <section class="relative pt-16 pb-20 md:pt-24 md:pb-32 px-4 sm:px-6 lg:px-8 max-w-7xl mx-auto text-center">
    <div class="inline-flex items-center gap-2 px-3.5 py-1.5 rounded-full border border-violet-200 bg-violet-50 text-violet-700 text-xs font-bold mb-6">
      <span class="w-2 h-2 rounded-full bg-violet-600 badge-pulse"></span>
      Official Platform • Built for ${industry}
    </div>

    <h1 class="text-4xl sm:text-6xl lg:text-7xl font-black tracking-tight text-slate-900 max-w-4xl mx-auto leading-[1.1]">
      ${params.heroHeadline ? params.heroHeadline.replace(new RegExp(safeName, 'gi'), `<span class="morn-gradient-text">${safeName}</span>`) : `Scale your operations with <span class="morn-gradient-text">${safeName}</span>`}
    </h1>

    <p class="mt-6 text-base sm:text-xl text-slate-600 max-w-2xl mx-auto leading-relaxed">
      ${params.heroSubheadline || safeTagline}
    </p>

    <div class="mt-8 flex flex-col sm:flex-row items-center justify-center gap-4">
      <a href="#pricing" class="w-full sm:w-auto px-8 py-4 rounded-xl text-sm font-extrabold text-white bg-violet-600 hover:bg-violet-700 transition shadow-xl shadow-violet-600/25 flex items-center justify-center gap-2">
        Start Free Trial
        <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2.5" d="M14 5l7 7m0 0l-7 7m7-7H3"/></svg>
      </a>
      <a href="#features" class="w-full sm:w-auto px-8 py-4 rounded-xl text-sm font-bold text-slate-700 bg-white hover:bg-slate-50 border border-slate-300 transition shadow-sm">
        Explore Solutions
      </a>
    </div>

    <!-- Product Showcase -->
    <div class="mt-14 max-w-5xl mx-auto rounded-3xl border border-slate-200/90 bg-white p-3 sm:p-5 shadow-2xl">
      <div class="rounded-2xl overflow-hidden border border-slate-200 bg-slate-900 text-white">
        ${
          imageUrl
            ? `<img src="${imageUrl}" alt="${safeName} Visual Showcase" loading="lazy" class="w-full max-h-[500px] object-cover object-center" />`
            : `<div class="p-8 sm:p-14 text-center bg-gradient-to-b from-slate-900 to-slate-950">
              <div class="w-16 h-16 mx-auto rounded-2xl bg-violet-500/20 text-violet-400 flex items-center justify-center mb-4">
                <svg class="w-8 h-8" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9.75 17L9 20l-1 1h8l-1-1-.75-3M3 13h18M5 17h14a2 2 0 002-2V5a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z"/></svg>
              </div>
              <h3 class="text-xl font-bold text-white">${safeName} Executive Hub</h3>
              <p class="text-slate-400 text-xs sm:text-sm mt-2 max-w-md mx-auto">Real-time collaboration, predictive analytics, and automated milestone tracking.</p>
              <div class="mt-8 grid grid-cols-2 sm:grid-cols-4 gap-3 max-w-2xl mx-auto text-left">
                <div class="p-3.5 rounded-xl bg-slate-800/80 border border-slate-700"><div class="text-violet-400 font-bold text-base">99.9%</div><div class="text-[10px] text-slate-400">Guaranteed Uptime</div></div>
                <div class="p-3.5 rounded-xl bg-slate-800/80 border border-slate-700"><div class="text-emerald-400 font-bold text-base">10x Speed</div><div class="text-[10px] text-slate-400">Sprint Acceleration</div></div>
                <div class="p-3.5 rounded-xl bg-slate-800/80 border border-slate-700"><div class="text-blue-400 font-bold text-base">Real-time</div><div class="text-[10px] text-slate-400">Team Collaboration</div></div>
                <div class="p-3.5 rounded-xl bg-slate-800/80 border border-slate-700"><div class="text-pink-400 font-bold text-base">Bank-Grade</div><div class="text-[10px] text-slate-400">Encrypted Storage</div></div>
              </div>
            </div>`
        }
      </div>
    </div>
  </section>

  <!-- Metrics Bar -->
  <section class="border-y border-slate-200 bg-white py-12">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 grid grid-cols-2 md:grid-cols-4 gap-8 text-center">
      <div>
        <div class="text-3xl font-black text-slate-900">10,000+</div>
        <div class="text-xs text-slate-500 mt-1 font-bold">Active Operators</div>
      </div>
      <div>
        <div class="text-3xl font-black text-violet-600">4.9 / 5.0</div>
        <div class="text-xs text-slate-500 mt-1 font-bold">Customer Satisfaction</div>
      </div>
      <div>
        <div class="text-3xl font-black text-emerald-600">&lt; 150ms</div>
        <div class="text-xs text-slate-500 mt-1 font-bold">API Latency</div>
      </div>
      <div>
        <div class="text-3xl font-black text-indigo-600">$4.2M+</div>
        <div class="text-xs text-slate-500 mt-1 font-bold">Value Unlocked</div>
      </div>
    </div>
  </section>

  <!-- Features Section -->
  <section id="features" class="py-20 md:py-28 px-4 sm:px-6 lg:px-8 max-w-7xl mx-auto">
    <div class="text-center max-w-3xl mx-auto mb-16">
      <span class="text-violet-600 text-xs font-black uppercase tracking-wider">Features</span>
      <h2 class="text-3xl sm:text-4xl font-black text-slate-900 mt-2">Built for high velocity teams</h2>
      <p class="text-slate-600 text-sm sm:text-base mt-4">Every component has been engineered to accelerate execution, eliminate bottlenecks, and compound results.</p>
    </div>

    <div class="grid grid-cols-1 md:grid-cols-3 gap-8">
      ${(params.features && params.features.length > 0 ? params.features : [
        { title: 'Automated Workflows', description: 'Eliminate repetitive tasks with trigger-based operational routines and instant team delegations.', icon: '⚡' },
        { title: 'Zero-Trust Security', description: 'Comprehensive audit logging, role-based access management, and automated regulatory compliance.', icon: '🛡️' },
        { title: 'Predictive Metrics', description: 'Turn pipeline telemetry into clear actionable forecasts so leadership can make decisions with conviction.', icon: '📈' }
      ]).map(f => `
        <div class="morn-card-hover p-8 rounded-2xl border border-slate-200 bg-white shadow-sm">
          <div class="w-12 h-12 rounded-xl bg-violet-100 text-violet-600 flex items-center justify-center font-bold text-xl mb-6">${f.icon || '⚡'}</div>
          <h3 class="text-lg font-bold text-slate-900">${f.title}</h3>
          <p class="text-slate-600 text-xs leading-relaxed mt-2.5">${f.description}</p>
        </div>
      `).join('')}
    </div>
  </section>

  <!-- Pricing Section -->
  <section id="pricing" class="py-20 md:py-28 bg-white border-t border-slate-200 px-4 sm:px-6 lg:px-8">
    <div class="max-w-7xl mx-auto text-center">
      <span class="text-violet-600 text-xs font-black uppercase tracking-wider">Pricing Plans</span>
      <h2 class="text-3xl sm:text-4xl font-black text-slate-900 mt-2">Transparent plans that scale with you</h2>
      <p class="text-slate-600 text-sm mt-3">Simple pricing without surprises. Upgrade or cancel anytime.</p>

      <!-- Billing Toggle -->
      <div class="mt-8 flex items-center justify-center gap-3">
        <span class="text-xs font-bold text-slate-600">Monthly</span>
        <label class="relative inline-flex items-center cursor-pointer">
          <input type="checkbox" id="billing-toggle" class="sr-only peer">
          <div class="w-11 h-6 bg-slate-300 peer-focus:outline-none rounded-full peer peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-slate-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:bg-violet-600"></div>
        </label>
        <span class="text-xs font-bold text-slate-900 flex items-center gap-1.5">
          Annually
          <span class="px-2 py-0.5 rounded-full bg-emerald-100 text-emerald-700 text-[10px] font-extrabold">Save 20%</span>
        </span>
      </div>

      <div class="grid grid-cols-1 md:grid-cols-3 gap-8 max-w-5xl mx-auto mt-12 text-left">
        <!-- Starter -->
        <div class="p-8 rounded-2xl border border-slate-200 bg-slate-50 flex flex-col justify-between">
          <div>
            <h3 class="text-base font-bold text-slate-900">Starter</h3>
            <p class="text-xs text-slate-500 mt-1">For solo operators and early MVPs.</p>
            <div class="mt-4 flex items-baseline gap-1">
              <span id="price-starter" class="text-3xl font-black text-slate-900">$19</span>
              <span class="billing-period text-xs text-slate-500">/month</span>
            </div>
            <ul class="mt-6 space-y-3 text-xs text-slate-700 font-medium">
              <li class="flex items-center gap-2"><span class="text-emerald-600 font-bold">✓</span> Up to 5 projects</li>
              <li class="flex items-center gap-2"><span class="text-emerald-600 font-bold">✓</span> Community support</li>
              <li class="flex items-center gap-2"><span class="text-emerald-600 font-bold">✓</span> Core analytics dashboard</li>
            </ul>
          </div>
          <a href="#cta" class="mt-8 block text-center py-3 rounded-xl border border-slate-300 bg-white hover:bg-slate-100 text-slate-900 text-xs font-bold transition">Get Started</a>
        </div>

        <!-- Growth (Popular) -->
        <div class="p-8 rounded-2xl border-2 border-violet-600 bg-white flex flex-col justify-between relative shadow-xl shadow-violet-600/10">
          <div class="absolute -top-3.5 left-1/2 -translate-x-1/2 px-3 py-0.5 rounded-full bg-violet-600 text-white text-[10px] font-black uppercase tracking-wider">Most Popular</div>
          <div>
            <h3 class="text-base font-bold text-slate-900">Growth</h3>
            <p class="text-xs text-slate-500 mt-1">For scaling teams moving fast.</p>
            <div class="mt-4 flex items-baseline gap-1">
              <span id="price-growth" class="text-3xl font-black text-slate-900">$49</span>
              <span class="billing-period text-xs text-slate-500">/month</span>
            </div>
            <ul class="mt-6 space-y-3 text-xs text-slate-700 font-medium">
              <li class="flex items-center gap-2"><span class="text-emerald-600 font-bold">✓</span> Unlimited active projects</li>
              <li class="flex items-center gap-2"><span class="text-emerald-600 font-bold">✓</span> Priority 24/7 support</li>
              <li class="flex items-center gap-2"><span class="text-emerald-600 font-bold">✓</span> Advanced telemetry & AI insights</li>
              <li class="flex items-center gap-2"><span class="text-emerald-600 font-bold">✓</span> Custom domain linking</li>
            </ul>
          </div>
          <a href="#cta" class="mt-8 block text-center py-3 rounded-xl bg-violet-600 hover:bg-violet-700 text-white text-xs font-extrabold transition shadow-lg shadow-violet-600/25">Start 14-Day Free Trial</a>
        </div>

        <!-- Scale -->
        <div class="p-8 rounded-2xl border border-slate-200 bg-slate-50 flex flex-col justify-between">
          <div>
            <h3 class="text-base font-bold text-slate-900">Enterprise</h3>
            <p class="text-xs text-slate-500 mt-1">Dedicated infrastructure & SLAs.</p>
            <div class="mt-4 flex items-baseline gap-1">
              <span id="price-scale" class="text-3xl font-black text-slate-900">$149</span>
              <span class="billing-period text-xs text-slate-500">/month</span>
            </div>
            <ul class="mt-6 space-y-3 text-xs text-slate-700 font-medium">
              <li class="flex items-center gap-2"><span class="text-emerald-600 font-bold">✓</span> Dedicated success architect</li>
              <li class="flex items-center gap-2"><span class="text-emerald-600 font-bold">✓</span> SOC2 & HIPAA compliant security</li>
              <li class="flex items-center gap-2"><span class="text-emerald-600 font-bold">✓</span> Custom integrations & SLAs</li>
            </ul>
          </div>
          <a href="#cta" class="mt-8 block text-center py-3 rounded-xl border border-slate-300 bg-white hover:bg-slate-100 text-slate-900 text-xs font-bold transition">Contact Enterprise Sales</a>
        </div>
      </div>
    </div>
  </section>

  <!-- FAQ Accordion -->
  <section id="faq" class="py-20 max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
    <div class="text-center mb-12">
      <span class="text-violet-600 text-xs font-black uppercase tracking-wider">FAQ</span>
      <h2 class="text-3xl font-black text-slate-900 mt-2">Frequently asked questions</h2>
    </div>

    <div class="space-y-3">
      <div class="faq-item rounded-xl border border-slate-200 bg-white p-5">
        <button class="faq-trigger w-full flex items-center justify-between text-left text-sm font-bold text-slate-900">
          <span>How fast can our team onboard with ${safeName}?</span>
          <svg class="faq-icon w-4 h-4 text-slate-400 transition-transform" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7"/></svg>
        </button>
        <div class="faq-content hidden mt-3 text-xs text-slate-600 leading-relaxed">
          Most teams launch their initial workflows in under 15 minutes. Our guided setup imports your existing context effortlessly.
        </div>
      </div>

      <div class="faq-item rounded-xl border border-slate-200 bg-white p-5">
        <button class="faq-trigger w-full flex items-center justify-between text-left text-sm font-bold text-slate-900">
          <span>Can I connect a custom domain?</span>
          <svg class="faq-icon w-4 h-4 text-slate-400 transition-transform" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7"/></svg>
        </button>
        <div class="faq-content hidden mt-3 text-xs text-slate-600 leading-relaxed">
          Yes! You can connect custom domains on Growth and Enterprise tiers with automated SSL provisioning.
        </div>
      </div>

      <div class="faq-item rounded-xl border border-slate-200 bg-white p-5">
        <button class="faq-trigger w-full flex items-center justify-between text-left text-sm font-bold text-slate-900">
          <span>Can I download the entire website source code?</span>
          <svg class="faq-icon w-4 h-4 text-slate-400 transition-transform" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7"/></svg>
        </button>
        <div class="faq-content hidden mt-3 text-xs text-slate-600 leading-relaxed">
          Absolutely. You own 100% of the code. Click "Download Code" at any time to export the full ZIP package.
        </div>
      </div>
    </div>
  </section>

  <!-- CTA Banner -->
  <section id="cta" class="py-20 px-4 sm:px-6 lg:px-8 max-w-5xl mx-auto text-center">
    <div class="p-10 sm:p-14 rounded-3xl bg-gradient-to-tr from-violet-600 to-indigo-700 text-white shadow-2xl">
      <h2 class="text-3xl sm:text-4xl font-black">Ready to scale with ${safeName}?</h2>
      <p class="text-violet-100 text-sm mt-3 max-w-xl mx-auto">Join thousands of operators accelerating their business operations today.</p>
      
      <form id="cta-form" class="mt-8 flex flex-col sm:flex-row items-center justify-center gap-3 max-w-md mx-auto">
        <input type="email" required placeholder="Enter your work email" class="w-full px-4 py-3 rounded-xl bg-white text-slate-900 text-xs focus:outline-none font-medium shadow-sm">
        <button type="submit" class="w-full sm:w-auto shrink-0 px-6 py-3 rounded-xl bg-slate-900 hover:bg-slate-800 text-white text-xs font-bold transition shadow-md">
          Request Early Access
        </button>
      </form>

      <div id="cta-success" class="hidden mt-6 p-4 rounded-xl bg-white/20 text-xs font-bold text-white">
        ✓ Thank you! We have reserved your early access spot.
      </div>
    </div>
  </section>
  </main>

  <!-- Footer -->
  <footer class="border-t border-slate-200 py-10 px-4 sm:px-6 lg:px-8 max-w-7xl mx-auto text-center text-xs text-slate-500 flex flex-col sm:flex-row items-center justify-between gap-4">
    <div>&copy; ${new Date().getFullYear()} ${safeName}. All rights reserved.</div>
    <div class="flex gap-6">
      <a href="#" class="hover:text-slate-800">Privacy Policy</a>
      <a href="#" class="hover:text-slate-800">Terms of Service</a>
      <a href="#" class="hover:text-slate-800">Security</a>
    </div>
  </footer>

  <script src="./src/main.js"></script>
</body>
</html>`;

  return {
    indexHtml,
    stylesCss,
    mainJs,
    packageJson,
    readmeMd,
  };
}

export const WebsiteStudio: React.FC<WebsiteStudioProps> = ({ startup, onClose }) => {
  const storageKey = `mornai_websites_${startup.id}`;
  const activeIdKey = `mornai_active_website_id_${startup.id}`;
  const draftPromptKey = `mornai_website_prompt_${startup.id}`;

  // Body scroll lock so background workspace never scrolls or peeks through
  useEffect(() => {
    const prevOverflow = document.body.style.overflow;
    document.body.style.overflow = 'hidden';
    return () => {
      document.body.style.overflow = prevOverflow;
    };
  }, []);

  const [projects, setProjects] = useState<WebsiteProject[]>(() => {
    try {
      const stored = localStorage.getItem(storageKey);
      if (stored) {
        const parsed = JSON.parse(stored);
        if (Array.isArray(parsed) && parsed.length > 0) return parsed;
      }
    } catch {}
    return [];
  });

  const [activeProjectId, setActiveProjectId] = useState<string>(() => {
    try {
      const savedActive = localStorage.getItem(activeIdKey);
      if (savedActive) return savedActive;
    } catch {}
    return '';
  });

  // Prompt persistence across page changes
  const [promptText, setPromptText] = useState<string>(() => {
    try {
      return localStorage.getItem(draftPromptKey) || '';
    } catch {
      return '';
    }
  });

  const [isSidebarOpen, setIsSidebarOpen] = useState(true);
  const [viewMode, setViewMode] = useState<'preview' | 'code'>('preview');
  const [viewportMode, setViewportMode] = useState<'desktop' | 'mobile'>('desktop');
  const [activeCodeFile, setActiveCodeFile] = useState<'index.html' | 'styles.css' | 'main.js' | 'package.json' | 'readme.md'>('index.html');

  const [productPhoto, setProductPhoto] = useState<string>('');
  const [isGenerating, setIsGenerating] = useState(false);
  const [progressPercent, setProgressPercent] = useState<number>(0);
  const [progressStep, setProgressStep] = useState<string>('');
  const [copiedCode, setCopiedCode] = useState(false);

  // New Project Name Modal
  const [showNewProjectModal, setShowNewProjectModal] = useState(false);
  const [newProjectNameInput, setNewProjectNameInput] = useState('');

  const fileInputRef = useRef<HTMLInputElement>(null);

  // Sync draft prompt text to localStorage
  useEffect(() => {
    try {
      localStorage.setItem(draftPromptKey, promptText);
    } catch {}
  }, [promptText, draftPromptKey]);

  // Sync projects to localStorage
  useEffect(() => {
    try {
      localStorage.setItem(storageKey, JSON.stringify(projects));
    } catch (e) {
      console.warn('Failed to persist website projects:', e);
    }
  }, [projects, storageKey]);

  // Sync active project id
  useEffect(() => {
    try {
      if (activeProjectId) localStorage.setItem(activeIdKey, activeProjectId);
    } catch {}
  }, [activeProjectId, activeIdKey]);

  const activeProject = useMemo(() => {
    if (!projects.length) return null;
    return projects.find((p) => p.id === activeProjectId) || projects[0] || null;
  }, [projects, activeProjectId]);

  const handleImageSelect = (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (!file) return;
    const reader = new FileReader();
    reader.onload = () => {
      if (typeof reader.result === 'string') {
        setProductPhoto(reader.result);
      }
    };
    reader.readAsDataURL(file);
  };

  const handleRemoveImage = () => {
    setProductPhoto('');
    if (fileInputRef.current) fileInputRef.current.value = '';
  };

  const handleOpenNewProjectModal = () => {
    setNewProjectNameInput('');
    setShowNewProjectModal(true);
  };

  const handleConfirmCreateProject = (e: React.FormEvent) => {
    e.preventDefault();
    const safeTitle = newProjectNameInput.trim();
    if (!safeTitle) return;

    const files = buildProjectFiles({
      startupName: startup.name,
      tagline: startup.tagline,
      prompt: '',
      industry: startup.industry,
    });

    const newProj: WebsiteProject = {
      id: `proj-${Date.now()}`,
      title: safeTitle,
      tagline: startup.tagline || 'Startup project',
      prompt: '',
      code: files.indexHtml,
      stylesCss: files.stylesCss,
      mainJs: files.mainJs,
      packageJson: files.packageJson,
      readmeMd: files.readmeMd,
      createdAt: Date.now(),
      updatedAt: Date.now(),
    };

    setProjects((prev) => [newProj, ...prev]);
    setActiveProjectId(newProj.id);
    setShowNewProjectModal(false);
    setNewProjectNameInput('');
  };

  const handleDeleteProject = (id: string, e: React.MouseEvent) => {
    e.stopPropagation();
    const filtered = projects.filter((p) => p.id !== id);
    setProjects(filtered);
    if (activeProjectId === id) {
      setActiveProjectId(filtered[0]?.id || '');
    }
  };

  const handleGenerateWebsite = async (overridePrompt?: string) => {
    const activePrompt = (overridePrompt || promptText).trim() || startup.tagline || startup.pitch || `Modern intelligent platform for ${startup.name}`;
    setIsGenerating(true);
    setProgressPercent(15);
    setProgressStep('Analyzing startup vision & target audience…');

    try {
      const t1 = setTimeout(() => {
        setProgressPercent(40);
        setProgressStep('Structuring multi-file project & UI components…');
      }, 700);

      const t2 = setTimeout(() => {
        setProgressPercent(70);
        setProgressStep('Writing responsive HTML5, styles.css & main.js…');
      }, 1600);

      const t3 = setTimeout(() => {
        setProgressPercent(90);
        setProgressStep('Compiling interactive scripts & live preview…');
      }, 2500);

      // AI blueprint call
      const data = await postMornAI<{
        title?: string;
        tagline?: string;
        heroHeadline?: string;
        heroSubheadline?: string;
        features?: Array<{ title: string; description: string; icon?: string }>;
        pricingTiers?: Array<{ name: string; priceMonthly: string; priceAnnual: string; description: string; features?: string[] }>;
        faq?: Array<{ question: string; answer: string }>;
        ctaHeadline?: string;
        pages?: string[];
        sections?: string[];
        visualDirection?: string;
      }>('website-blueprint', {
        startup,
        prompt: activePrompt,
        imageProvided: Boolean(productPhoto),
      });

      clearTimeout(t1);
      clearTimeout(t2);
      clearTimeout(t3);

      setProgressPercent(100);
      setProgressStep('Complete! Website live in preview.');

      const newTitle = data?.title || `${startup.name} Website`;
      const newTagline = data?.tagline || activePrompt || startup.tagline || '';

      const files = buildProjectFiles({
        startupName: startup.name,
        tagline: newTagline,
        prompt: activePrompt,
        industry: startup.industry,
        sections: data?.sections,
        visualDirection: data?.visualDirection,
        imageUrl: productPhoto || activeProject?.imagePreview,
        heroHeadline: data?.heroHeadline,
        heroSubheadline: data?.heroSubheadline,
        features: data?.features,
        pricingTiers: data?.pricingTiers,
        faq: data?.faq,
        ctaHeadline: data?.ctaHeadline,
      });

      if (activeProject) {
        // Update existing project
        setProjects((prev) =>
          prev.map((p) =>
            p.id === activeProject.id
              ? {
                  ...p,
                  title: newTitle,
                  tagline: newTagline,
                  prompt: activePrompt,
                  imagePreview: productPhoto || p.imagePreview,
                  code: files.indexHtml,
                  stylesCss: files.stylesCss,
                  mainJs: files.mainJs,
                  packageJson: files.packageJson,
                  readmeMd: files.readmeMd,
                  updatedAt: Date.now(),
                }
              : p
          )
        );
      } else {
        // Create initial project for their business
        const newProj: WebsiteProject = {
          id: `proj-${Date.now()}`,
          title: newTitle,
          tagline: newTagline,
          prompt: activePrompt,
          imagePreview: productPhoto,
          code: files.indexHtml,
          stylesCss: files.stylesCss,
          mainJs: files.mainJs,
          packageJson: files.packageJson,
          readmeMd: files.readmeMd,
          createdAt: Date.now(),
          updatedAt: Date.now(),
        };
        setProjects([newProj]);
        setActiveProjectId(newProj.id);
      }

      setTimeout(() => {
        setIsGenerating(false);
        setProgressPercent(0);
        setProgressStep('');
      }, 700);
    } catch (err) {
      console.warn('Fallback website build applied:', err);
      setProgressPercent(100);
      setProgressStep('Ready! Applied responsive design blueprint.');

      const files = buildProjectFiles({
        startupName: startup.name,
        tagline: activePrompt || startup.tagline || '',
        prompt: activePrompt,
        industry: startup.industry,
        imageUrl: productPhoto,
      });

      if (activeProject) {
        setProjects((prev) =>
          prev.map((p) =>
            p.id === activeProject.id
              ? {
                  ...p,
                  code: files.indexHtml,
                  stylesCss: files.stylesCss,
                  mainJs: files.mainJs,
                  packageJson: files.packageJson,
                  readmeMd: files.readmeMd,
                  updatedAt: Date.now(),
                }
              : p
          )
        );
      } else {
        const newProj: WebsiteProject = {
          id: `proj-${Date.now()}`,
          title: `${startup.name} Website`,
          tagline: startup.tagline || '',
          prompt: activePrompt,
          imagePreview: productPhoto,
          code: files.indexHtml,
          stylesCss: files.stylesCss,
          mainJs: files.mainJs,
          packageJson: files.packageJson,
          readmeMd: files.readmeMd,
          createdAt: Date.now(),
          updatedAt: Date.now(),
        };
        setProjects([newProj]);
        setActiveProjectId(newProj.id);
      }

      setTimeout(() => {
        setIsGenerating(false);
        setProgressPercent(0);
        setProgressStep('');
      }, 700);
    }
  };

  // Download project as true .ZIP archive
  const handleDownloadZip = () => {
    if (!activeProject) return;

    const files = buildProjectFiles({
      startupName: startup.name,
      tagline: activeProject.tagline,
      prompt: activeProject.prompt,
      industry: startup.industry,
      imageUrl: activeProject.imagePreview,
    });

    const zipBlob = createZipBlob([
      { name: 'index.html', content: activeProject.code || files.indexHtml },
      { name: 'src/styles.css', content: activeProject.stylesCss || files.stylesCss },
      { name: 'src/main.js', content: activeProject.mainJs || files.mainJs },
      { name: 'package.json', content: activeProject.packageJson || files.packageJson },
      { name: 'README.md', content: activeProject.readmeMd || files.readmeMd },
    ]);

    const url = URL.createObjectURL(zipBlob);
    const link = document.createElement('a');
    link.href = url;
    const safeFilename = (activeProject.title || startup.name || 'website')
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/(^-|-$)/g, '');
    link.download = `${safeFilename}.zip`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const handleCopyCurrentCode = async () => {
    const codeToCopy = getActiveCodeContent();
    if (!codeToCopy) return;
    try {
      await navigator.clipboard.writeText(codeToCopy);
      setCopiedCode(true);
      setTimeout(() => setCopiedCode(false), 2000);
    } catch {
      const textarea = document.createElement('textarea');
      textarea.value = codeToCopy;
      document.body.appendChild(textarea);
      textarea.select();
      document.execCommand('copy');
      document.body.removeChild(textarea);
      setCopiedCode(true);
      setTimeout(() => setCopiedCode(false), 2000);
    }
  };

  const getActiveCodeContent = (): string => {
    if (!activeProject) return '';
    switch (activeCodeFile) {
      case 'index.html':
        return activeProject.code;
      case 'styles.css':
        return activeProject.stylesCss || '';
      case 'main.js':
        return activeProject.mainJs || '';
      case 'package.json':
        return activeProject.packageJson || '';
      case 'readme.md':
        return activeProject.readmeMd || '';
      default:
        return activeProject.code;
    }
  };

  // Preview Document that inlines CSS & JS for 100% accurate standalone live preview
  const livePreviewHtml = useMemo(() => {
    if (!activeProject?.code) return '';
    let html = activeProject.code;
    if (activeProject.stylesCss) {
      html = html.replace(
        '<link rel="stylesheet" href="./src/styles.css">',
        `<style>\n${activeProject.stylesCss}\n</style>`
      );
    }
    if (activeProject.mainJs) {
      html = html.replace(
        '<script src="./src/main.js"></script>',
        `<script>\n${activeProject.mainJs}\n</script>`
      );
    }
    return html;
  }, [activeProject]);

  const suggestionPills = [
    '⚡ Add pricing table with monthly & annual toggle',
    '💬 Add customer reviews & interactive FAQ',
    '🚀 SaaS landing page with conversion hero',
    '🛡️ Enterprise security & compliance showcase',
    '📱 Mobile application launch showcase',
  ];

  // Portaled to document.body to completely cover header, footer, and workspace
  return createPortal(
    <div className="fixed inset-0 z-[999999] w-full h-[100dvh] max-h-[100dvh] bg-white text-slate-900 flex flex-col overflow-hidden overscroll-none font-['Plus_Jakarta_Sans',sans-serif]">
      {/* Top Header Bar (White Theme - Fully Mobile Responsive) */}
      <header className="h-14 sm:h-16 shrink-0 border-b border-slate-200 bg-white px-3 sm:px-6 flex items-center justify-between gap-2 sm:gap-3 shadow-xs">
        {/* Left: Sidebar Toggle + Startup Info */}
        <div className="flex items-center gap-2 sm:gap-3 min-w-0">
          <button
            type="button"
            onClick={() => setIsSidebarOpen((prev) => !prev)}
            className="p-1.5 sm:p-2 rounded-xl border border-slate-200 bg-slate-50 hover:bg-slate-100 text-slate-600 transition shrink-0"
            title={isSidebarOpen ? 'Hide Projects Sidebar' : 'Show Projects Sidebar'}
            aria-label="Toggle projects sidebar"
          >
            {isSidebarOpen ? <ChevronLeft className="h-4 w-4" /> : <ChevronRight className="h-4 w-4" />}
          </button>

          <div className="flex items-center gap-2 min-w-0">
            <div className="h-7 w-7 sm:h-8 sm:w-8 rounded-xl bg-violet-600 flex items-center justify-center font-black text-xs text-white shrink-0 shadow-sm">
              {startup.name.charAt(0).toUpperCase()}
            </div>
            <div className="min-w-0 hidden md:block">
              <h1 className="text-xs sm:text-sm font-extrabold text-slate-900 truncate max-w-[130px] lg:max-w-[220px]">
                {activeProject?.title || `${startup.name} Website Studio`}
              </h1>
              <p className="text-[9px] sm:text-[10px] font-semibold text-slate-500 truncate">
                {activeProject ? 'Saved & Live' : 'Build website with Morn AI'}
              </p>
            </div>
          </div>
        </div>

        {/* Center: Preview vs Code & Desktop vs Mobile */}
        <div className="flex items-center gap-1.5 sm:gap-3">
          {/* View mode toggle */}
          <div className="flex items-center rounded-xl bg-slate-100 p-0.5 sm:p-1 border border-slate-200 text-xs">
            <button
              type="button"
              onClick={() => setViewMode('preview')}
              className={`flex items-center gap-1 sm:gap-1.5 px-2.5 sm:px-3 py-1 sm:py-1.5 rounded-lg font-bold text-xs transition ${
                viewMode === 'preview'
                  ? 'bg-white text-violet-700 shadow-xs'
                  : 'text-slate-500 hover:text-slate-900'
              }`}
            >
              <Eye className="h-3.5 w-3.5" />
              <span>Preview</span>
            </button>
            <button
              type="button"
              onClick={() => setViewMode('code')}
              className={`flex items-center gap-1 sm:gap-1.5 px-2.5 sm:px-3 py-1 sm:py-1.5 rounded-lg font-bold text-xs transition ${
                viewMode === 'code'
                  ? 'bg-white text-violet-700 shadow-xs'
                  : 'text-slate-500 hover:text-slate-900'
              }`}
            >
              <Code className="h-3.5 w-3.5" />
              <span>Code</span>
            </button>
          </div>

          {/* Viewport toggle (when in Preview mode, desktop/tablet only) */}
          {viewMode === 'preview' && activeProject && (
            <div className="hidden md:flex items-center rounded-xl bg-slate-100 p-1 border border-slate-200 text-xs">
              <button
                type="button"
                onClick={() => setViewportMode('desktop')}
                className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg font-bold transition ${
                  viewportMode === 'desktop'
                    ? 'bg-white text-slate-900 shadow-xs'
                    : 'text-slate-500 hover:text-slate-900'
                }`}
              >
                <Monitor className="h-3.5 w-3.5" />
                <span>Desktop</span>
              </button>
              <button
                type="button"
                onClick={() => setViewportMode('mobile')}
                className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg font-bold transition ${
                  viewportMode === 'mobile'
                    ? 'bg-white text-slate-900 shadow-xs'
                    : 'text-slate-500 hover:text-slate-900'
                }`}
              >
                <Smartphone className="h-3.5 w-3.5" />
                <span>Mobile</span>
              </button>
            </div>
          )}
        </div>

        {/* Right: Download ZIP & Prominent RED Cross Button */}
        <div className="flex items-center gap-1.5 sm:gap-2.5">
          {activeProject && (
            <button
              type="button"
              onClick={handleDownloadZip}
              className="flex items-center gap-1.5 px-2.5 sm:px-3.5 py-1.5 sm:py-2 rounded-xl bg-violet-600 hover:bg-violet-700 text-white text-xs font-bold transition shadow-xs shrink-0"
              title="Download complete project files as .ZIP"
            >
              <Download className="h-3.5 w-3.5" />
              <span className="hidden sm:inline">Download ZIP</span>
            </button>
          )}

          {/* Red Cross Button */}
          <button
            type="button"
            onClick={onClose}
            className="flex items-center justify-center h-8 w-8 sm:h-9 sm:w-9 rounded-xl bg-rose-500 hover:bg-rose-600 text-white transition shadow-sm active:scale-95 shrink-0"
            aria-label="Close Website Page"
            title="Close Website Page"
          >
            <X className="h-4 w-4 stroke-[2.5]" />
          </button>
        </div>
      </header>

      {/* Progress Bar (when generating) */}
      {isGenerating && (
        <div className="w-full bg-violet-50/70 border-b border-violet-100 px-6 py-2 flex flex-col gap-1 transition-all">
          <div className="flex items-center justify-between text-xs font-bold text-violet-900">
            <span className="flex items-center gap-2">
              <RefreshCw className="h-3.5 w-3.5 animate-spin text-violet-600" />
              {progressStep}
            </span>
            <span className="font-mono text-violet-700">{progressPercent}%</span>
          </div>
          <div className="w-full h-1.5 rounded-full bg-violet-200 overflow-hidden">
            <div
              className="h-full bg-gradient-to-r from-violet-600 to-indigo-600 transition-all duration-300"
              style={{ width: `${progressPercent}%` }}
            />
          </div>
        </div>
      )}

      {/* Main Studio Workspace */}
      <div className="flex-1 min-h-0 flex relative overflow-hidden bg-slate-50">
        {/* Mobile Backdrop for Sidebar */}
        {isSidebarOpen && (
          <div
            className="fixed inset-0 z-40 bg-slate-900/40 backdrop-blur-xs sm:hidden"
            onClick={() => setIsSidebarOpen(false)}
          />
        )}

        {/* Left Sidebar: Saved Projects (Mobile Overlay + Desktop Inline) */}
        <aside
          className={`fixed inset-y-0 left-0 z-50 h-full border-r border-slate-200 bg-white flex flex-col transition-all duration-300 ease-in-out sm:static sm:z-auto ${
            isSidebarOpen
              ? 'translate-x-0 w-72 max-w-[85vw] shadow-2xl sm:shadow-none'
              : '-translate-x-full sm:translate-x-0 sm:w-0 sm:overflow-hidden sm:border-r-0'
          }`}
        >
          <div className="p-3.5 border-b border-slate-200 flex items-center justify-between">
            <div className="flex items-center gap-2">
              <FolderKanban className="h-4 w-4 text-violet-600" />
              <span className="text-xs font-extrabold uppercase tracking-wider text-slate-800">
                Your Projects
              </span>
              <span className="px-1.5 py-0.5 rounded-full bg-slate-100 text-[10px] font-bold text-slate-600">
                {projects.length}
              </span>
            </div>

            <div className="flex items-center gap-1.5">
              {/* New Project Button */}
              <button
                type="button"
                onClick={() => {
                  handleOpenNewProjectModal();
                  if (typeof window !== 'undefined' && window.innerWidth < 640) setIsSidebarOpen(false);
                }}
                className="flex items-center gap-1 px-2.5 py-1 rounded-lg bg-violet-600 hover:bg-violet-700 text-white text-[11px] font-bold transition shadow-xs"
                title="Create new website project"
              >
                <Plus className="h-3 w-3" />
                <span>New</span>
              </button>

              {/* Close Sidebar Button on Mobile */}
              <button
                type="button"
                onClick={() => setIsSidebarOpen(false)}
                className="sm:hidden p-1 rounded-lg text-slate-400 hover:text-slate-600 hover:bg-slate-100 transition"
                aria-label="Close sidebar"
              >
                <X className="h-4 w-4" />
              </button>
            </div>
          </div>

          <div className="flex-1 min-h-0 overflow-y-auto p-2.5 space-y-2 overscroll-contain">
            {projects.length === 0 ? (
              <div className="p-5 text-center text-xs text-slate-400">
                No saved websites yet. Enter a description below to build one!
              </div>
            ) : (
              projects.map((proj) => {
                const active = proj.id === activeProject?.id;
                return (
                  <div
                    key={proj.id}
                    onClick={() => {
                      setActiveProjectId(proj.id);
                      if (typeof window !== 'undefined' && window.innerWidth < 640) setIsSidebarOpen(false);
                    }}
                    className={`group relative p-3 rounded-xl border text-left cursor-pointer transition ${
                      active
                        ? 'border-violet-600 bg-violet-50/70 text-violet-950 shadow-xs'
                        : 'border-slate-200 bg-white text-slate-600 hover:border-slate-300 hover:bg-slate-50'
                    }`}
                  >
                    <div className="flex items-start justify-between gap-2">
                      <div className="min-w-0 flex-1">
                        <p className={`text-xs font-bold truncate ${active ? 'text-violet-900 font-extrabold' : 'text-slate-800'}`}>
                          {proj.title}
                        </p>
                        <p className="text-[10px] text-slate-500 truncate mt-0.5">
                          {proj.tagline || 'Startup Landing Page'}
                        </p>
                        <p className="text-[9px] text-slate-400 mt-1 font-mono">
                          {new Date(proj.updatedAt).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                        </p>
                      </div>

                      <button
                        type="button"
                        onClick={(e) => handleDeleteProject(proj.id, e)}
                        className="opacity-0 group-hover:opacity-100 p-1 rounded-md text-slate-400 hover:text-rose-600 hover:bg-rose-50 transition"
                        title="Delete project"
                      >
                        <Trash2 className="h-3.5 w-3.5" />
                      </button>
                    </div>
                  </div>
                );
              })
            )}
          </div>
        </aside>

        {/* Central Display & Bottom Prompt Dock */}
        <main className="flex-1 min-h-0 flex flex-col relative bg-slate-100/60 overflow-hidden">
          {/* Top Canvas Viewport */}
          <div className="flex-1 min-h-0 relative flex items-center justify-center p-2 sm:p-5 overflow-auto">
            {viewMode === 'preview' ? (
              activeProject ? (
                /* Active Project Live Preview */
                <div
                  className={`transition-all duration-300 h-full flex flex-col ${
                    viewportMode === 'mobile'
                      ? 'w-full sm:w-[385px] max-w-full h-full sm:h-[760px] max-h-full sm:rounded-[40px] sm:border-[10px] sm:border-slate-900 shadow-2xl overflow-hidden rounded-xl border border-slate-200 bg-white'
                      : 'w-full h-full rounded-xl sm:rounded-2xl border border-slate-200 bg-white shadow-lg overflow-hidden'
                  }`}
                >
                  {/* Browser top-bar mockup (Desktop mode) */}
                  {viewportMode === 'desktop' && (
                    <div className="h-9 shrink-0 bg-slate-100 border-b border-slate-200 px-4 flex items-center gap-3 text-xs text-slate-500">
                      <div className="flex items-center gap-1.5">
                        <span className="w-2.5 h-2.5 rounded-full bg-rose-400" />
                        <span className="w-2.5 h-2.5 rounded-full bg-amber-400" />
                        <span className="w-2.5 h-2.5 rounded-full bg-emerald-400" />
                      </div>
                      <div className="flex-1 max-w-sm mx-auto rounded-lg bg-white px-3 py-1 text-[11px] font-mono text-slate-600 truncate text-center border border-slate-200 shadow-xs">
                        https://{startup.name.toLowerCase().replace(/[^a-z0-9]/g, '')}.mornai.app
                      </div>
                    </div>
                  )}

                  {/* Sandboxed Iframe */}
                  <iframe
                    title="Live Website Preview"
                    srcDoc={livePreviewHtml}
                    className="w-full flex-1 border-0 bg-white"
                    sandbox="allow-scripts allow-modals allow-forms"
                  />
                </div>
              ) : (
                /* Welcome / Empty State: "Build website with Morn AI" */
                <div className="w-full max-w-2xl mx-auto my-auto rounded-2xl sm:rounded-3xl border border-slate-200 bg-white p-4 sm:p-10 text-center shadow-lg">
                  <div className="w-12 h-12 sm:w-16 sm:h-16 mx-auto rounded-2xl bg-violet-100 text-violet-600 flex items-center justify-center mb-3 sm:mb-5">
                    <Rocket className="h-6 w-6 sm:h-8 sm:w-8" />
                  </div>
                  <h2 className="text-xl sm:text-3xl font-black text-slate-900 tracking-tight">
                    Build website with Morn AI
                  </h2>
                  <p className="text-slate-600 text-xs sm:text-sm mt-2 sm:mt-3 max-w-lg mx-auto leading-relaxed">
                    Describe your startup concept, target audience, and key features below. Morn AI will design, write, and bundle a complete multi-file responsive website for <strong className="text-slate-900">{startup.name}</strong>.
                  </p>

                  <div className="mt-4 sm:mt-8 grid grid-cols-1 sm:grid-cols-3 gap-2.5 sm:gap-4 text-left">
                    <div className="p-3 sm:p-4 rounded-2xl border border-slate-100 bg-slate-50/70">
                      <div className="text-violet-600 font-extrabold text-xs uppercase tracking-wider">1. High-Impact Hero</div>
                      <p className="text-[11px] text-slate-500 mt-1 leading-relaxed">Dynamic value proposition, conversion CTAs, and product showcases.</p>
                    </div>
                    <div className="p-3 sm:p-4 rounded-2xl border border-slate-100 bg-slate-50/70">
                      <div className="text-indigo-600 font-extrabold text-xs uppercase tracking-wider">2. Interactive Code</div>
                      <p className="text-[11px] text-slate-500 mt-1 leading-relaxed">Pricing toggles, mobile drawers, and smooth animations in vanilla JS.</p>
                    </div>
                    <div className="p-3 sm:p-4 rounded-2xl border border-slate-100 bg-slate-50/70">
                      <div className="text-emerald-600 font-extrabold text-xs uppercase tracking-wider">3. ZIP Code Export</div>
                      <p className="text-[11px] text-slate-500 mt-1 leading-relaxed">Organized project files (HTML, CSS, JS, package.json) ready to deploy.</p>
                    </div>
                  </div>
                </div>
              )
            ) : (
              /* Google AI Studio Organized Code Explorer */
              <div className="w-full h-full rounded-xl sm:rounded-2xl border border-slate-200 bg-white shadow-lg flex flex-col sm:flex-row overflow-hidden">
                {/* Mobile Horizontal File Switcher Bar */}
                <div className="flex items-center gap-1.5 overflow-x-auto p-2 bg-slate-50 border-b border-slate-200 no-scrollbar sm:hidden shrink-0">
                  {[
                    { id: 'index.html', label: 'index.html', icon: <FileCode className="h-3.5 w-3.5 text-orange-500" /> },
                    { id: 'styles.css', label: 'styles.css', icon: <Palette className="h-3.5 w-3.5 text-blue-500" /> },
                    { id: 'main.js', label: 'main.js', icon: <FileCode className="h-3.5 w-3.5 text-amber-500" /> },
                    { id: 'package.json', label: 'package.json', icon: <Package className="h-3.5 w-3.5 text-emerald-500" /> },
                    { id: 'readme.md', label: 'README.md', icon: <FileText className="h-3.5 w-3.5 text-slate-500" /> },
                  ].map((f) => (
                    <button
                      key={f.id}
                      type="button"
                      onClick={() => setActiveCodeFile(f.id as any)}
                      className={`flex items-center gap-1.5 px-2.5 py-1.5 rounded-lg text-xs font-mono font-bold whitespace-nowrap transition ${
                        activeCodeFile === f.id
                          ? 'bg-violet-600 text-white shadow-xs'
                          : 'bg-white text-slate-600 border border-slate-200'
                      }`}
                    >
                      {f.icon}
                      <span>{f.label}</span>
                    </button>
                  ))}
                </div>

                {/* File Tree Explorer (Left - Desktop Only) */}
                <div className="hidden sm:flex w-56 shrink-0 border-r border-slate-200 bg-slate-50 flex-col">
                  <div className="p-3 border-b border-slate-200 flex items-center justify-between text-xs font-bold text-slate-700">
                    <span className="flex items-center gap-1.5">
                      <Layers className="h-4 w-4 text-violet-600" />
                      Project Files
                    </span>
                    <span className="text-[10px] font-mono text-slate-400">5 files</span>
                  </div>

                  <div className="flex-1 overflow-y-auto p-2 space-y-1 text-xs font-mono">
                    <div className="px-2 py-1 text-[11px] text-slate-400 font-bold">
                      📁 {(activeProject?.title || startup.name).toLowerCase().replace(/[^a-z0-9]+/g, '-')}/
                    </div>

                    <button
                      type="button"
                      onClick={() => setActiveCodeFile('index.html')}
                      className={`w-full flex items-center gap-2 px-3 py-2 rounded-lg text-left transition ${
                        activeCodeFile === 'index.html'
                          ? 'bg-violet-100 text-violet-900 font-bold'
                          : 'text-slate-600 hover:bg-slate-100'
                      }`}
                    >
                      <FileCode className="h-4 w-4 text-orange-500" />
                      <span>index.html</span>
                    </button>

                    <div className="pl-3 space-y-1">
                      <div className="px-2 py-0.5 text-[10px] text-slate-400">📁 src/</div>
                      <button
                        type="button"
                        onClick={() => setActiveCodeFile('styles.css')}
                        className={`w-full flex items-center gap-2 px-3 py-1.5 rounded-lg text-left transition ${
                          activeCodeFile === 'styles.css'
                            ? 'bg-violet-100 text-violet-900 font-bold'
                            : 'text-slate-600 hover:bg-slate-100'
                        }`}
                      >
                        <Palette className="h-3.5 w-3.5 text-blue-500" />
                        <span>styles.css</span>
                      </button>

                      <button
                        type="button"
                        onClick={() => setActiveCodeFile('main.js')}
                        className={`w-full flex items-center gap-2 px-3 py-1.5 rounded-lg text-left transition ${
                          activeCodeFile === 'main.js'
                            ? 'bg-violet-100 text-violet-900 font-bold'
                            : 'text-slate-600 hover:bg-slate-100'
                        }`}
                      >
                        <FileCode className="h-3.5 w-3.5 text-amber-500" />
                        <span>main.js</span>
                      </button>
                    </div>

                    <button
                      type="button"
                      onClick={() => setActiveCodeFile('package.json')}
                      className={`w-full flex items-center gap-2 px-3 py-2 rounded-lg text-left transition ${
                        activeCodeFile === 'package.json'
                          ? 'bg-violet-100 text-violet-900 font-bold'
                          : 'text-slate-600 hover:bg-slate-100'
                      }`}
                    >
                      <Package className="h-4 w-4 text-emerald-500" />
                      <span>package.json</span>
                    </button>

                    <button
                      type="button"
                      onClick={() => setActiveCodeFile('readme.md')}
                      className={`w-full flex items-center gap-2 px-3 py-2 rounded-lg text-left transition ${
                        activeCodeFile === 'readme.md'
                          ? 'bg-violet-100 text-violet-900 font-bold'
                          : 'text-slate-600 hover:bg-slate-100'
                      }`}
                    >
                      <FileText className="h-4 w-4 text-slate-500" />
                      <span>README.md</span>
                    </button>
                  </div>
                </div>

                {/* Code Editor Panel (Right) */}
                <div className="flex-1 min-w-0 flex flex-col bg-white">
                  <div className="h-10 shrink-0 border-b border-slate-200 px-4 flex items-center justify-between text-xs text-slate-500 bg-slate-50">
                    <span className="font-mono font-bold text-slate-800 flex items-center gap-2">
                      <FileCode className="h-4 w-4 text-violet-600" />
                      {activeCodeFile}
                    </span>
                    <div className="flex items-center gap-2">
                      <button
                        type="button"
                        onClick={handleCopyCurrentCode}
                        className="px-3 py-1 rounded-lg border border-slate-200 bg-white hover:bg-slate-100 text-slate-700 text-xs font-semibold flex items-center gap-1.5 shadow-xs"
                      >
                        {copiedCode ? <Check className="h-3.5 w-3.5 text-emerald-600" /> : <Copy className="h-3.5 w-3.5" />}
                        <span>{copiedCode ? 'Copied' : 'Copy'}</span>
                      </button>
                      <button
                        type="button"
                        onClick={handleDownloadZip}
                        className="px-3 py-1 rounded-lg bg-violet-600 hover:bg-violet-700 text-white text-xs font-bold flex items-center gap-1.5 shadow-xs"
                      >
                        <Download className="h-3.5 w-3.5" />
                        <span>Download ZIP</span>
                      </button>
                    </div>
                  </div>

                  <div className="flex-1 min-h-0 overflow-auto p-4 font-mono text-xs text-slate-800 leading-relaxed bg-white selection:bg-violet-200">
                    <pre className="whitespace-pre">{getActiveCodeContent()}</pre>
                  </div>
                </div>
              </div>
            )}
          </div>

          {/* Bottom Docked Prompt Input Bar (Permanently Visible & Sticky on Mobile) */}
          <div className="shrink-0 sticky bottom-0 z-40 border-t border-slate-200 bg-white px-3 py-2 sm:px-4 sm:py-3 shadow-xl pb-[max(0.6rem,env(safe-area-inset-bottom))]">
            {/* Quick Ideas Chips with Top Padding Fix */}
            <div className="flex items-center gap-1.5 sm:gap-2 overflow-x-auto pt-0.5 pb-1.5 px-0.5 no-scrollbar text-[10px] sm:text-[11px]">
              <span className="text-slate-500 font-bold shrink-0 flex items-center gap-1">
                <Sparkles className="h-3 w-3 text-violet-600" /> Quick ideas:
              </span>
              {suggestionPills.map((pill) => (
                <button
                  key={pill}
                  type="button"
                  onClick={() => {
                    setPromptText(pill);
                    void handleGenerateWebsite(pill);
                  }}
                  className="shrink-0 px-2.5 sm:px-3 py-1 sm:py-1.5 rounded-full border border-slate-200 bg-slate-50 hover:border-violet-400 hover:bg-violet-50 text-slate-700 hover:text-violet-900 transition shadow-xs font-medium"
                >
                  {pill}
                </button>
              ))}
            </div>

            {/* Selected Product Picture Thumbnail with Red/Slate Cross Button */}
            {productPhoto && (
              <div className="relative inline-flex items-center gap-2 mb-2 p-1.5 pr-2.5 rounded-xl border border-violet-200 bg-violet-50 max-w-full">
                <img src={productPhoto} alt="Product preview" className="h-8 w-8 sm:h-10 sm:w-10 rounded-lg object-cover border border-violet-200 shrink-0" />
                <div className="min-w-0 text-left">
                  <p className="text-[10px] sm:text-[11px] font-bold text-violet-950 truncate">Picture attached</p>
                  <p className="text-[8px] sm:text-[9px] text-violet-600 truncate">Featured on hero section</p>
                </div>
                {/* Cross Button to remove picture */}
                <button
                  type="button"
                  onClick={handleRemoveImage}
                  className="ml-1.5 p-1 rounded-full bg-rose-100 hover:bg-rose-500 text-rose-600 hover:text-white transition shrink-0"
                  title="Remove selected picture"
                  aria-label="Remove selected picture"
                >
                  <X className="h-3.5 w-3.5" />
                </button>
              </div>
            )}

            {/* Input & Action Row */}
            <div className="flex items-center gap-1.5 sm:gap-2.5">
              {/* Photo Upload Attachment Button */}
              <input
                ref={fileInputRef}
                type="file"
                accept="image/*"
                onChange={handleImageSelect}
                className="hidden"
                id="website-photo-upload"
              />
              <label
                htmlFor="website-photo-upload"
                className="cursor-pointer shrink-0 p-2 sm:p-2.5 rounded-xl border border-slate-200 bg-slate-50 hover:bg-slate-100 hover:border-violet-300 text-slate-600 hover:text-violet-600 transition flex items-center justify-center shadow-xs"
                title="Attach product picture"
              >
                <ImagePlus className="h-4 w-4" />
              </label>

              {/* Multiline Prompt Input */}
              <div className="flex-1 min-w-0 relative">
                <input
                  id="website-studio-prompt-input"
                  name="website-prompt"
                  type="text"
                  value={promptText}
                  onChange={(e) => setPromptText(e.target.value)}
                  onKeyDown={(e) => {
                    if (e.key === 'Enter' && !e.shiftKey) {
                      e.preventDefault();
                      void handleGenerateWebsite();
                    }
                  }}
                  placeholder="Describe your website or ask for changes..."
                  className="w-full px-3.5 sm:px-4 py-2 sm:py-2.5 rounded-xl border border-slate-300 bg-white text-xs sm:text-sm text-slate-900 placeholder-slate-400 focus:outline-none focus:border-violet-600 focus:ring-2 focus:ring-violet-100 font-medium shadow-xs select-text"
                />
              </div>

              {/* Generate Website Button */}
              <button
                type="button"
                onClick={() => void handleGenerateWebsite()}
                disabled={isGenerating}
                className="shrink-0 px-3 sm:px-5 py-2 sm:py-2.5 rounded-xl bg-violet-600 hover:bg-violet-700 disabled:opacity-50 text-white text-xs sm:text-sm font-extrabold transition shadow-md shadow-violet-600/20 flex items-center gap-1.5 active:scale-95"
              >
                {isGenerating ? (
                  <>
                    <RefreshCw className="h-4 w-4 animate-spin" />
                    <span className="hidden xs:inline">Building…</span>
                  </>
                ) : (
                  <>
                    <Sparkles className="h-4 w-4" />
                    <span className="hidden xs:inline">{projects.length > 0 ? 'Update Website' : 'Generate Website'}</span>
                    <span className="xs:hidden">{projects.length > 0 ? 'Update' : 'Generate'}</span>
                  </>
                )}
              </button>
            </div>
          </div>
        </main>
      </div>

      {/* Modal: Ask User for Project Name (No Default Name) */}
      {showNewProjectModal && (
        <div className="fixed inset-0 z-[1000000] flex items-center justify-center bg-slate-900/50 backdrop-blur-xs p-4">
          <div className="w-full max-w-md rounded-2xl border border-slate-200 bg-white p-6 shadow-2xl">
            <div className="flex items-center justify-between pb-3 border-b border-slate-100">
              <h3 className="text-sm font-extrabold text-slate-900">Name Your Website Project</h3>
              <button
                type="button"
                onClick={() => setShowNewProjectModal(false)}
                className="p-1 rounded-lg text-slate-400 hover:text-slate-600"
              >
                <X className="h-4 w-4" />
              </button>
            </div>

            <form onSubmit={handleConfirmCreateProject} className="mt-4 space-y-4">
              <div>
                <label className="block text-xs font-bold text-slate-700 mb-1">
                  Project Title
                </label>
                <input
                  type="text"
                  required
                  autoFocus
                  placeholder="e.g. SaaS Launchpad v2, Minimal Storefront"
                  value={newProjectNameInput}
                  onChange={(e) => setNewProjectNameInput(e.target.value)}
                  className="w-full px-3.5 py-2 rounded-xl border border-slate-300 text-xs sm:text-sm text-slate-900 focus:outline-none focus:border-violet-600 focus:ring-2 focus:ring-violet-100"
                />
              </div>

              <div className="flex items-center justify-end gap-2 pt-2">
                <button
                  type="button"
                  onClick={() => setShowNewProjectModal(false)}
                  className="px-4 py-2 rounded-xl border border-slate-200 bg-slate-50 hover:bg-slate-100 text-xs font-bold text-slate-600 transition"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  disabled={!newProjectNameInput.trim()}
                  className="px-5 py-2 rounded-xl bg-violet-600 hover:bg-violet-700 disabled:opacity-50 text-white text-xs font-extrabold transition shadow-xs"
                >
                  Create Project
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>,
    document.body
  );
};
